spring.application.name=ticketing-drools
server.port=8083
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.task.scheduling.pool.size=5
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
# ? FIX: Register JavaTimeModule for LocalDateTime
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
#spring.jackson.deserialization.fail-on-unknown-properties=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=false
